name: Build odoo base image
on:
  push:
    branches:
      - '[0-9]+[0-9]+.[0-9]+'
jobs:
  Base:
    name: Build base image
    runs-on:
      group: socket-staging
    steps:
    - name: push the image
      run: | 
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Smart-IT-Kirkham/sit-docker/actions/workflows/base-image-trigger.yml/dispatches -d '{"ref":"'${{ github.ref_name }}'"}'